spring:
  redis:
    database: 15
    host: 127.0.0.1
    password: 123456
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 5000
env: 222333
